'use client'
import { Geist, Geist_Mono } from "next/font/google";
import { Calculator } from "lucide-react";
import "./globals.css";
import Link from "next/link";
import { usePathname } from "next/navigation";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const path = usePathname()
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
           <div className="container mx-auto px-4 py-6 max-w-6xl">
        <header className="bg-blue-600 text-white shadow-lg">
          <div className="container mx-auto px-4 py-4">
            <div className="flex items-center gap-3">
              <Calculator size={28} />
              <h1 className="text-xl md:text-2xl font-bold">
                Ambalaj Maliyet Hesaplama
              </h1>
            </div>
          </div>
        </header>
        <div className="bg-white rounded-lg shadow-md mb-6">
          <div className="flex border-b">
            <Link
              href="/home"
              className={`flex-1 py-4 px-4 md:px-6 font-semibold transition-colors text-sm md:text-base ${
                path ==="/home"
                  ? "bg-blue-50 text-blue-600 border-b-2 border-blue-600"
                  : "text-gray-600 hover:bg-gray-50"
              }`}
            >
              Kullanıcı Paneli
            </Link>
            <Link
              href="/admin"
              className={`flex-1 py-4 px-4 md:px-6 font-semibold transition-colors text-sm md:text-base ${
               path ==="/admin"
                  ? "bg-blue-50 text-blue-600 border-b-2 border-blue-600"
                  : "text-gray-600 hover:bg-gray-50"
              }`}
            >
              Admin Paneli
            </Link>
          </div>
        </div>
        <div className="container mx-auto px-4 py-6 max-w-6xl">{children}</div>
        </div>
        
      </body>
    </html>
  );
}
